# Generated by Django 5.1.4 on 2024-12-19 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_news_after_name_news_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': ('News',)},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='after_name',
            new_name='athor_name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
        migrations.AddField(
            model_name='news',
            name='created_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
